"""add_user_sub

Revision ID: 56056c40e5b1
Revises: a0d1bf95ed0e
Create Date: 2026-04-07 17:03:56.110755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56056c40e5b1'
down_revision: Union[str, Sequence[str], None] = 'a0d1bf95ed0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_sub'), 'users', ['sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sub'), table_name='users')
    op.drop_column('users', 'sub')
    # ### end Alembic commands ###
